# Generated by Django 5.0.8 on 2026-01-14 19:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('asset_type', models.CharField(choices=[('vm', 'VM'), ('server', 'Serveur'), ('nas', 'NAS/Storage'), ('network', 'Réseau'), ('other', 'Autre')], default='server', max_length=20)),
                ('ip_or_host', models.CharField(help_text='IP ou hostname', max_length=255)),
                ('tags', models.CharField(blank=True, help_text='Ex: prod,pve,pbs,site-a', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('ping', 'Ping (ICMP)'), ('tcp_port', 'TCP Port'), ('http', 'HTTP/HTTPS'), ('ssl_expiry', 'SSL Expiry')], max_length=20)),
                ('interval_seconds', models.PositiveIntegerField(default=60)),
                ('target', models.CharField(blank=True, help_text='Ex: https://site.tld ou hostname', max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=3)),
                ('expected_status', models.PositiveIntegerField(default=200)),
                ('ssl_days_threshold', models.PositiveIntegerField(default=14)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='critical', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('ack_by', models.CharField(blank=True, max_length=150)),
                ('ack_at', models.DateTimeField(blank=True, null=True)),
                ('monitor_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.check')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('action', models.CharField(help_text='Ex: restart_service, proxmox_stop_vm, etc.', max_length=150)),
                ('payload_json', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('monitor_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.check')),
            ],
            options={
                'indexes': [models.Index(fields=['recorded_at'], name='core_checkr_recorde_f19e2a_idx'), models.Index(fields=['monitor_check', 'recorded_at'], name='core_checkr_monitor_107963_idx')],
            },
        ),
    ]
